[package]
name = "leds"
version = "0.1.0"
authors = ["Terje Uglebakken <430725+teug91@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artnet_protocol="0.2.0"
